<Project>
  <PropertyGroup>
    <AnalysisLevel>latest</AnalysisLevel>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <Deterministic>true</Deterministic>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <FileVersion>0.1.0.0</FileVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <InformationalVersion>$(Version)</InformationalVersion>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Version>0.1.0</Version>
  </PropertyGroup>
</Project>
